### ISSUE TITLE
error signaled after adding assignment, but assignment still added

### ISSUE THREAD

**Issue by joerromano** [jbclements/admiral-edu-server#34]
In the 'author' page creating a new assignment, I created a new one with the following description

```
name: Flags
id: flags
description: Supplemental homework 1.
steps:
  - id: final-submission
    instructions: Submit your final code here.
```

After clicking "Validate and Submit", I was given an alert box indicating there was an error.  However, when clicking the button again, I was given a different alert box saying the assignment already exists.

After navigating to the main page, the assignment did indeed exist and was correct.
